# -*- mode:toml; -*-
[module.thread-prothos]
    incfiles = [
        "thread/PortalPool.hh",
        "thread/Thread.hh",
        "thread/ThreadId.hh",
        "thread/ThreadStack.hh",
        "thread/ThreadState.hh",
    ]

    appfiles = [
        "thread/PortalPool.cc",
        "thread/Thread.cc",
        "thread/ThreadId.cc",
        "thread/ThreadStack.cc",
        "thread/ThreadState.cc"
    ]
