# -*- mode:toml; -*-
[module.app-init-prothos]
    initappfiles = [ "app/init.cc" ]
    provides = [ "app/init" ]
    requires = [ "tag/platform/linux"]

    makefile_head = '''
TARGETS += app/init.elf
'''
    makefile_body = '''
app/init: $(INITAPPFILES_OBJ) $(APPFILES_OBJ) $(CRTFILES_OBJ)
	$(APP_CXX) $(APP_LDFLAGS) $(APP_CXXFLAGS) -nostdlib -o $@ runtime/start.o runtime/crtbegin.o $(INITAPPFILES_OBJ) $(APPFILES_OBJ) $(APP_LIBS) runtime/crtend.o
	$(NM)  $@ | cut -d " " -f 1,3 | c++filt -t > init.sym
	$(OBJDUMP) -dS $@ | c++filt > init.disasm
	$(STRIP) $@
'''
